name: $(Date:yyyy.MM.dd.HHmm)

resources:
  containers:
  - container: dotnet_latest
    image: microsoft/dotnet:latest
    options: '--name dotnet_latest -v /usr/bin/docker:/tmp/docker:ro'

jobs:
- job: check_tag
  displayName: Check tag
  pool:
    vmImage: vs2017-win2016
  steps:
    - template: publish/check.tag.yml

- job: windows
  displayName: Windows
  pool:
    vmImage: vs2017-win2016
  strategy:
    matrix:
      Q8-x86:
        QuantumName: Q8
        PlatformName: x86
      Q8-x64:
        QuantumName: Q8
        PlatformName: x64
      Q8-OpenMP-x64:
        QuantumName: Q8-OpenMP
        PlatformName: x64
      Q8-AnyCPU:
        QuantumName: Q8
        PlatformName: Any CPU
      Q16-x86:
        QuantumName: Q16
        PlatformName: x86
      Q16-x64:
        QuantumName: Q16
        PlatformName: x64
      Q16-OpenMP-x64:
        QuantumName: Q16-OpenMP
        PlatformName: x64
      Q16-AnyCPU:
        QuantumName: Q16
        PlatformName: Any CPU
      Q16-HDRI-x86:
        QuantumName: Q16-HDRI
        PlatformName: x86
      Q16-HDRI-x64:
        QuantumName: Q16-HDRI
        PlatformName: x64
      Q16-HDRI-OpenMP-x64:
        QuantumName: Q16-HDRI-OpenMP
        PlatformName: x64
      Q16-HDRI-AnyCPU:
        QuantumName: Q16-HDRI
        PlatformName: Any CPU
  steps:
    - template: build/windows/build.yml
  dependsOn:
  - check_tag

- job: linux
  displayName: Linux Q8/Q16/Q16-HDRI
  pool:
    vmImage: Ubuntu 16.04
  container: dotnet_latest
  steps:
    - script: /tmp/docker exec -t -u 0 dotnet_latest $(Build.SourcesDirectory)/build/linux/install.sudo.sh
      displayName: Install sudo
    - template: build/linux/build.yml
  dependsOn:
  - check_tag

- job: macos
  displayName: MacOS Q8/Q16/Q16-HDRI
  pool:
    vmImage: macOS 10.13
  steps:
    - template: build/macos/build.yml
  dependsOn:
  - check_tag
